# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.



def fib_sum(highest_term)
  fib = [0,1]

  while fib[-1] < highest_term && (fib[-1] + fib[-2]) < highest_term
    fib.push(fib[-1] + fib[-2])
  end

  fib.select { |x| x % 2 == 0}.inject(:+)
end


p fib_sum(4_000_000)